/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admissionform.mz;

import DbService.mz.TrainingsDbService;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import mz.beans.Trainings;

/**
 *
 * @author Aman
 */
public class AddTrainingsFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrainingsInternalFrame
     */
    public AddTrainingsFrame() {
        initComponents();
        try {
            trainingIdTxtField.setText(String.valueOf(TrainingsDbService.getLastTrainingId() + 1));
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            Logger.getLogger(AddmissionFormFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    AddTrainingsFrame(JMenuItem trainingsAddMenuItem) {
        this();
        addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                trainingsAddMenuItem.setEnabled(true);
                trainingNameTxtField.setText("");
                durationComboBox.setSelectedIndex(0);
                feeTxtField.setText("");
                discriptionTxtArea.setText("");
                installmentsButtonGroup.clearSelection();
                installmentsSpinner.setValue(0);
                installmentsSpinner.setEnabled(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        installmentsButtonGroup = new javax.swing.ButtonGroup();
        trainingsLabel = new javax.swing.JLabel();
        trainingNameLabel = new javax.swing.JLabel();
        trainingNameTxtField = new javax.swing.JTextField();
        durationLabel = new javax.swing.JLabel();
        durationComboBox = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        feeTxtField = new javax.swing.JTextField();
        feeLabel = new javax.swing.JLabel();
        discriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        discriptionTxtArea = new javax.swing.JTextArea();
        installmentsLabel = new javax.swing.JLabel();
        availBtn = new javax.swing.JRadioButton();
        notAvailBtn = new javax.swing.JRadioButton();
        trainingIDLabel = new javax.swing.JLabel();
        trainingIdTxtField = new javax.swing.JTextField();
        installmentsSpinner = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        trainingsLabel.setFont(new java.awt.Font("Times New Roman", 1, 52)); // NOI18N
        trainingsLabel.setText("Trainings");

        trainingNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        trainingNameLabel.setText("Training Name:");

        trainingNameTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        durationLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        durationLabel.setText("Duration:");

        durationComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        durationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "       ", "2 months", "3 months", "4 months", "6 months", "12 months", "18 months", " ", " ", " " }));

        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        feeTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        feeLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        feeLabel.setText("Fee:");

        discriptionLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        discriptionLabel.setText("Discription:");

        discriptionTxtArea.setColumns(20);
        discriptionTxtArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        discriptionTxtArea.setRows(5);
        jScrollPane1.setViewportView(discriptionTxtArea);

        installmentsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        installmentsLabel.setText("Installments:");

        installmentsButtonGroup.add(availBtn);
        availBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        availBtn.setText("Available");
        availBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availBtnActionPerformed(evt);
            }
        });

        installmentsButtonGroup.add(notAvailBtn);
        notAvailBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        notAvailBtn.setText("Not Available");
        notAvailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notAvailBtnActionPerformed(evt);
            }
        });

        trainingIDLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        trainingIDLabel.setText("Training Id:");

        trainingIdTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        installmentsSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        installmentsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        installmentsSpinner.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(trainingsLabel)
                .addGap(531, 531, 531))
            .addGroup(layout.createSequentialGroup()
                .addGap(650, 650, 650)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trainingIDLabel)
                    .addComponent(trainingNameLabel)
                    .addComponent(durationLabel)
                    .addComponent(feeLabel)
                    .addComponent(installmentsLabel)
                    .addComponent(discriptionLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(durationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(feeTxtField)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(trainingNameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addComponent(trainingIdTxtField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(availBtn)
                        .addGap(6, 6, 6)
                        .addComponent(notAvailBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(installmentsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {durationComboBox, feeTxtField, jScrollPane1, trainingNameTxtField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(trainingsLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainingNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainingNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainingIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainingIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feeLabel))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(discriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(installmentsLabel)
                    .addComponent(availBtn)
                    .addComponent(notAvailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(installmentsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {durationComboBox, feeTxtField, trainingIdTxtField, trainingNameTxtField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {discriptionLabel, durationLabel, feeLabel, installmentsLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {availBtn, notAvailBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getInstallments() {
        if (availBtn.isSelected()) {
            return "available";
        } else {
            return "not Available";
        }
    }
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            String trainingName = trainingNameTxtField.getText().trim();
            String duration = (String) durationComboBox.getSelectedItem();
            String fee = feeTxtField.getText().trim();
            String description = discriptionTxtArea.getText().trim();

            if (!trainingName.isEmpty() && !duration.isEmpty() && !fee.isEmpty() && !description.isEmpty() && availBtn.isSelected() || notAvailBtn.isSelected()) {
                Trainings training;
                training = new Trainings(trainingName, duration, fee, description, getInstallments(), (int) installmentsSpinner.getValue());
                boolean check = TrainingsDbService.addTraining(training);
                if (check) {
                    JOptionPane.showMessageDialog(null, "Training Added");
                    trainingNameTxtField.setText("");
                    int newTrainingId = Integer.parseInt(trainingIdTxtField.getText());
                    trainingIdTxtField.setText(newTrainingId + 1 + "");
                    durationComboBox.setSelectedIndex(0);
                    feeTxtField.setText("");
                    discriptionTxtArea.setText("");
                    installmentsButtonGroup.clearSelection();
                    installmentsSpinner.setValue(0);
                    installmentsSpinner.setEnabled(false);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please fill all the fields", "ERROR", JOptionPane.OK_OPTION);
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            Logger.getLogger(AddTrainingsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void availBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availBtnActionPerformed
        installmentsSpinner.setEnabled(true);
        installmentsSpinner.setValue(1);
    }//GEN-LAST:event_availBtnActionPerformed

    private void notAvailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notAvailBtnActionPerformed
        installmentsSpinner.setEnabled(false);
        installmentsSpinner.setValue(0);
    }//GEN-LAST:event_notAvailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JRadioButton availBtn;
    private javax.swing.JLabel discriptionLabel;
    private javax.swing.JTextArea discriptionTxtArea;
    private javax.swing.JComboBox durationComboBox;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JTextField feeTxtField;
    private javax.swing.ButtonGroup installmentsButtonGroup;
    private javax.swing.JLabel installmentsLabel;
    private javax.swing.JSpinner installmentsSpinner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton notAvailBtn;
    private javax.swing.JLabel trainingIDLabel;
    private javax.swing.JTextField trainingIdTxtField;
    private javax.swing.JLabel trainingNameLabel;
    private javax.swing.JTextField trainingNameTxtField;
    private javax.swing.JLabel trainingsLabel;
    // End of variables declaration//GEN-END:variables
}
