/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admissionform.mz;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;

/**
 *
 * @author Aman
 */
public class HomeWindow extends javax.swing.JFrame {

    AddmissionFormFrame addmissionFrame = null;
    EditSearchDeleteViewTraineeFrame editSearchDeleteViewTraineeFrame = null;
    AddTrainingsFrame addTrainingFrame = null;
    EditSearchDeleteViewTrainingsFrame editSearchDeleteViewTrainingsFrame = null;
    UpdateForm update = null;

    public HomeWindow() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        addmissionFrame = new AddmissionFormFrame(addTraineeMenuItem);
        editSearchDeleteViewTraineeFrame = new EditSearchDeleteViewTraineeFrame(editDeleteSearchViewTraineeMenuItem);
        addTrainingFrame = new AddTrainingsFrame(addTrainingsMenuItem);
        editSearchDeleteViewTrainingsFrame = new EditSearchDeleteViewTrainingsFrame(editSearchDeleteViewTrainingsMenuItem);
        update = new UpdateForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        traineeMenu = new javax.swing.JMenu();
        addTraineeMenuItem = new javax.swing.JMenuItem();
        jSeparator = new javax.swing.JPopupMenu.Separator();
        editDeleteSearchViewTraineeMenuItem = new javax.swing.JMenuItem();
        trainingsMenu = new javax.swing.JMenu();
        addTrainingsMenuItem = new javax.swing.JMenuItem();
        editSearchDeleteViewTrainingsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Window");

        desktopPane.setOpaque(false);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        traineeMenu.setText("Trainee");

        addTraineeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        addTraineeMenuItem.setText("Add");
        addTraineeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTraineeMenuItemActionPerformed(evt);
            }
        });
        traineeMenu.add(addTraineeMenuItem);
        traineeMenu.add(jSeparator);

        editDeleteSearchViewTraineeMenuItem.setText("Edit/Delete/Search/View");
        editDeleteSearchViewTraineeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDeleteSearchViewTraineeMenuItemActionPerformed(evt);
            }
        });
        traineeMenu.add(editDeleteSearchViewTraineeMenuItem);

        jMenuBar1.add(traineeMenu);

        trainingsMenu.setText("Trainings");

        addTrainingsMenuItem.setText("Add");
        addTrainingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrainingsMenuItemActionPerformed(evt);
            }
        });
        trainingsMenu.add(addTrainingsMenuItem);

        editSearchDeleteViewTrainingsMenuItem.setText("Edit/Search/Delete/View");
        editSearchDeleteViewTrainingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSearchDeleteViewTrainingsMenuItemActionPerformed(evt);
            }
        });
        trainingsMenu.add(editSearchDeleteViewTrainingsMenuItem);

        jMenuBar1.add(trainingsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addTraineeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTraineeMenuItemActionPerformed
        addFrame(addTraineeMenuItem,addmissionFrame);
    }//GEN-LAST:event_addTraineeMenuItemActionPerformed

    private void editDeleteSearchViewTraineeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDeleteSearchViewTraineeMenuItemActionPerformed
        addFrame(editDeleteSearchViewTraineeMenuItem,editSearchDeleteViewTraineeFrame);
    }//GEN-LAST:event_editDeleteSearchViewTraineeMenuItemActionPerformed

    private void addTrainingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrainingsMenuItemActionPerformed
        addFrame(addTrainingsMenuItem,addTrainingFrame);
    }//GEN-LAST:event_addTrainingsMenuItemActionPerformed

    private void editSearchDeleteViewTrainingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSearchDeleteViewTrainingsMenuItemActionPerformed
       addFrame(editSearchDeleteViewTrainingsMenuItem,editSearchDeleteViewTrainingsFrame);
    }//GEN-LAST:event_editSearchDeleteViewTrainingsMenuItemActionPerformed
    public void addFrame(JMenuItem menuItem,JInternalFrame frameToBeAdded){
         if (menuItem.isEnabled()) {
            desktopPane.add(frameToBeAdded);
            frameToBeAdded.setVisible(true);
            menuItem.setEnabled(false);

            try {
                frameToBeAdded.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(HomeWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addTraineeMenuItem;
    private javax.swing.JMenuItem addTrainingsMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editDeleteSearchViewTraineeMenuItem;
    private javax.swing.JMenuItem editSearchDeleteViewTrainingsMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator;
    private javax.swing.JMenu traineeMenu;
    private javax.swing.JMenu trainingsMenu;
    // End of variables declaration//GEN-END:variables
}
